### ISSUE TITLE
Is export.py script really working?

### ISSUE THREAD

**Issue by monurcank** [Darth-Kronos/YOSO_TensorRT#1]
I cloned the YOSO repo. Its demo.py is working as expected. Then I only copied your export.py script to the demo folder of the YOSO repo.
But, when I tried to use your export.py script, I got the following error:

<img width="1512" alt="image" src="https://github.com/Darth-Kronos/YOSO_TensorRT/assets/136856645/4768307a-8618-49fa-8f27-e2e5b81f826e">

Then, I removed "image" and directly used that tensor, but, then I got that error instead:

<img width="1512" alt="image" src="https://github.com/Darth-Kronos/YOSO_TensorRT/assets/136856645/962abb36-7ae5-4295-809e-97a2cdcaac31">

Is your repo really working?

**Comment by Darth-Kronos** [comment]
Exporting to TensorRT is still in development
